// import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "@/redux/provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
